"""Auto-generate state-pipeline preset YAMLs for all 48 lower-48 states.

Reads the canonical US-VA.yml as a template and substitutes state code (and
state-specific values where known). Skips states that already have a preset
(US-VA, US-MO) unless --force is passed.

Run:
    python scripts/generate_state_presets.py
"""
from __future__ import annotations
import argparse
from pathlib import Path

ROOT = Path(__file__).parent.parent
PRESETS_DIR = ROOT / "state_pipeline" / "presets"

# 48 lower-48 states (excludes AK, HI, DC which lack ResStock/Cambium 2022 coverage)
STATES = {
    'AL': 'Alabama', 'AR': 'Arkansas', 'AZ': 'Arizona', 'CA': 'California',
    'CO': 'Colorado', 'CT': 'Connecticut', 'DE': 'Delaware', 'FL': 'Florida',
    'GA': 'Georgia', 'IA': 'Iowa', 'ID': 'Idaho', 'IL': 'Illinois',
    'IN': 'Indiana', 'KS': 'Kansas', 'KY': 'Kentucky', 'LA': 'Louisiana',
    'MA': 'Massachusetts', 'MD': 'Maryland', 'ME': 'Maine', 'MI': 'Michigan',
    'MN': 'Minnesota', 'MO': 'Missouri', 'MS': 'Mississippi', 'MT': 'Montana',
    'NC': 'North Carolina', 'ND': 'North Dakota', 'NE': 'Nebraska',
    'NH': 'New Hampshire', 'NJ': 'New Jersey', 'NM': 'New Mexico', 'NV': 'Nevada',
    'NY': 'New York', 'OH': 'Ohio', 'OK': 'Oklahoma', 'OR': 'Oregon',
    'PA': 'Pennsylvania', 'RI': 'Rhode Island', 'SC': 'South Carolina',
    'SD': 'South Dakota', 'TN': 'Tennessee', 'TX': 'Texas', 'UT': 'Utah',
    'VA': 'Virginia', 'VT': 'Vermont', 'WA': 'Washington', 'WI': 'Wisconsin',
    'WV': 'West Virginia', 'WY': 'Wyoming',
}

TEMPLATE = """# Preset for {display_name} (US-{state_iso2})
# Auto-generated by scripts/generate_state_presets.py.
# See CLAUDE.md §4 for methodology.

region_code: US-{state_iso2}
parent_iso: US
subregion_type: state
state_iso2: {state_iso2}
display_name: {display_name}
output_slug: US-{state_iso2}

calendar_year: 2018  # ResStock TMY3 calendar (2018 non-leap, starts Monday)

# Pipeline parameters
n_timeslices: 6
# Clustering uses rep-day reconstruction on net load (cluster_days_repday).
# Optimizer self-terminates ~10-15 day peak slices; no cap needed.
peak_top_n_days: 1
max_peak_days: 365

# Industry shape mode: efs / flat / cambium_residual
industry_shape_mode: efs

# Cambium curtailment add-back (empty by default; set per-tech factors for high-VRE states)
curtailment_addback: {{}}

sources:
  bcue_dir: state-eps-data-repository/{state_iso2}/bldgs/BCEU
  industry_csv: state-eps-data-repository/{state_iso2}/indst/BIFUbC/BIFUbC-electricity.csv
  transport_dir: state-eps-data-repository/{state_iso2}/trans
  resstock_dir: ResStock SHELF/ResStock_Upgrade0/state={state_iso2}
  comstock_dir: ResStock SHELF/ComStock_tmy_release1/{state_iso2}
  legacy_shelf_dir: state-eps-data-repository/{state_iso2}/elec/SHELF
  legacy_syshecf_dir: state-eps-data-repository/{state_iso2}/elec/SYSHECF
  efs_zip: data/efs/EFSLoadProfile_Reference_Moderate.zip
  cambium_hourly_csv: data/cambium22_midcase_state_hourly/Cambium22_MidCase_hourly_{state_iso2}_2024.csv
  cambium_annual_csv: data/cambium22_midcase_state_hourly/Cambium22_MidCase_annual_state.csv
  cambium_year: 2024
  datacenter_annual_twh: 0.0

outputs:
  shelf_dir: state-eps-data-repository/{state_iso2}/elec/SHELF/_python_pipeline
  syshecf_dir: state-eps-data-repository/{state_iso2}/elec/SYSHECF/_python_pipeline
  excel_workbook_demand_shelf: state-eps-data-repository/{state_iso2}/elec/SHELF/_python_pipeline/{state_iso2} - Hourly Demand and SHELF.xlsx
  excel_workbook_syshecf: state-eps-data-repository/{state_iso2}/elec/SYSHECF/_python_pipeline/{state_iso2} - SYSHECF.xlsx
  validation_dir: output/validation/US-{state_iso2}

status: auto-generated
"""


def main(force: bool = False):
    PRESETS_DIR.mkdir(exist_ok=True, parents=True)
    written = 0
    skipped = 0
    for state, name in sorted(STATES.items()):
        path = PRESETS_DIR / f"US-{state}.yml"
        if path.exists() and not force:
            skipped += 1
            continue
        path.write_text(TEMPLATE.format(state_iso2=state, display_name=name))
        written += 1
        print(f"  wrote {path.name}")
    print(f"\nWrote {written} presets; skipped {skipped} existing (use --force to overwrite)")


if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('--force', action='store_true', help='overwrite existing presets')
    args = ap.parse_args()
    main(force=args.force)
